### ISSUE TITLE
Too low tire pressure on 18-wheeler

### ISSUE THREAD

**Issue by ge0rg** [hessu/aprs-symbols#1]
The 18-wheeler / semi-trailer symbol has barely noticeable wheels (except for the front one). This is especially apparent on a dark background, but also problematic on light ones.

Example: http://aprs.fi/info/?call=SQ9JDR-5

**Comment by hessu** [comment]
It is one of the new models, low floor, easy to load and unload, high vertical clearance inside.

I'll replace it with an older, more traditional trailer model.

**Comment by hessu** [comment]
This should be fixed in 4097d9df386b212c948113d5f941878628822cd7 - I increased the ground clearance of the 18-wheeler now. Should do better on rough rural roads.
