### ISSUE TITLE
Changing \$ from € to ¤

### ISSUE THREAD

**Issue by PhirePhly** [hessu/aprs-symbols#2]
The original symbol tile set uses a green square with a dollar sign in it to represent a bank or ATM. This symbol set instead uses a €. Both symbols fail to be international. Would you be opposed to instead using the scarab / CURRENCY SIGN U+00A4 symbol (¤), which is used to represent unspecific currency?

The counter-argument is that it is likely that fewer people would recognize the scarab as the correct symbol than recognize the Euro as the incorrect currency symbol.

https://en.wikipedia.org/wiki/Currency_sign_(typography)

**Comment by hessu** [comment]
I did a quick poll in the room here (statistically significant sample of 2 subjects, including myself) and 0% of the subjects knew what the ¤ symbol meant. One test subject guessed it was the symbol for a laundry dryer, which is not a bad guess.

I would assume very few knew about it, so I'd rather keep the € for now. Maybe switch to $ or £ in the next incarnation in 10 years, for balance. It's not exactly international, but at least someone knows what it is.

**Comment by PhirePhly** [comment]
Fair enough. I just wanted to make sure we considered the issue. I'll need to put some more thought into better ways to handle this localization issue.
