### ISSUE TITLE
COPYRIGHT compatibility

### ISSUE THREAD

**Issue by smarek** [hessu/aprs-symbols#3]
Hi,
i've recently published CSS/JS utlity rendering the APRS symbols, https://github.com/smarek/aprs-symbols

I've seen this project having complicated COPYRIGHT, due to several sources of data etc.

Is including your original COPYRIGHT within my project sufficient to fulfil your expectations about honoring work of yours and others?

Cheers!

**Comment by hessu** [comment]
Yes, that's fine by me.
