### ISSUE TITLE
48 and 128 raster renderings?

### ISSUE THREAD

**Issue by craigerl** [hessu/aprs-symbols#5]
__Raster_ renderings are available in 24x24, 48x48, 64x64 and 128x128 pixel""_"

I spotted 24 aand 64... 48 would be a sweet spot for my project.  thanks

**Comment by hessu** [comment]
Hi! I finally added some resolutions and the following are now available:
24, 32, 48, 56, 64, 128 and 256x256. All with @2x and @3x versions as well.
There's some overlap, but it's easier for me to import them to my projects with high-DPI support this way.
